name: test-8-slack-notification-line-breaks

on: [push]

jobs:
  slack-action:
    #if: ${{ false }}
    runs-on: windows-latest
    name: Test 8 [windows-latest]

    steps:
      - name: Send Slack Message 1/3
        uses: archive/github-actions-slack@master
        id: send-message-1
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
          slack-channel: C036UR2P5BM
          slack-text: |
            Test 8 - 1/3!

            This
            should
            have
            line
            breaks...

      - name: Result from "Send Slack Message"
        run: echo '${{ steps.send-message-1.outputs.slack-result }}'

      - name: Send Slack Message 2/3
        uses: archive/github-actions-slack@master
        id: send-message-2
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
          slack-channel: C036UR2P5BM
          slack-text: "Test 8 - 2/3!\n\nThis\nshould\nhave\nline\nbreaks..."

      - name: Result from "Send Slack Message"
        run: echo '${{ steps.send-message-2.outputs.slack-result }}'

      - name: Send Slack Message 3/3
        uses: archive/github-actions-slack@master
        id: send-message-3
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
          slack-channel: C036UR2P5BM
          slack-text: "${{ format('{0}\n\n```{1}```', 'Test 8 - 3/3', toJson(runner)) }}"

      - name: Result from "Send Slack Message"
        run: echo '${{ steps.send-message-3.outputs.slack-result }}'
